# Generated by Django 4.2.7 on 2023-12-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shop",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="shops_images/"),
        ),
        migrations.AddField(
            model_name="shop",
            name="pickup_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="raiting",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1 звезда"),
                    ("2", "2 звезда"),
                    ("3", "3 звезда"),
                    ("4", "4 звезда"),
                    ("5", "5 звезда"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
