# Generated by Django 4.2.7 on 2023-11-29 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_subcategory_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
