# Generated by Django 4.2.7 on 2023-12-03 15:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", unique=True
            ),
        ),
    ]
