# Generated by Django 4.2.7 on 2023-12-07 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
        ("products", "0006_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.shop",
            ),
        ),
    ]
